#############################################################################
# Makefile for building: qPaint
# Generated by qmake (2.01a) (Qt 4.6.3) on: ?? ????. 18 11:40:26 2012
# Project:  qPaint.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile qPaint.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUse_Separable_Gauss -DVirtual_Callback -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/GUI/gui.cpp \
		src/GUI/ImageScene.cpp \
		src/GUI/Validators.cpp \
		src/ArgParser/arg_parser.cpp \
		src/main.cpp \
		src/Engine/Filter.cpp \
		src/Engine/Engine.cpp \
		src/Engine/Callback.cpp \
		src/Engine/Filters/Hystogram.cpp \
		src/Engine/Filters/GreyWorld.cpp \
		src/Engine/Filters/Convolution.cpp \
		src/Engine/Filters/Sobel.cpp \
		src/Engine/Filters/Interpolation.cpp \
		src/Engine/Filters/Manually.cpp \
		src/Engine/Filters/Supplementary.cpp \
		src/Engine/Filters/GaussianS.cpp moc_gui.cpp \
		moc_ImageScene.cpp
OBJECTS       = gui.o \
		ImageScene.o \
		Validators.o \
		arg_parser.o \
		main.o \
		Filter.o \
		Engine.o \
		Callback.o \
		Hystogram.o \
		GreyWorld.o \
		Convolution.o \
		Sobel.o \
		Interpolation.o \
		Manually.o \
		Supplementary.o \
		GaussianS.o \
		moc_gui.o \
		moc_ImageScene.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qPaint.pro
QMAKE_TARGET  = qPaint
DESTDIR       = 
TARGET        = qPaint

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_gui.h ui_Manually.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qPaint.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile qPaint.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile qPaint.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qPaint1.0.0 || $(MKDIR) .tmp/qPaint1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qPaint1.0.0/ && $(COPY_FILE) --parents src/GUI/gui.h src/GUI/ImageScene.h src/GUI/Validators.h src/ArgParser/arg_parser.h src/Engine/Filter.h src/Engine/Engine.h src/Engine/Callback.h src/Engine/Filters/Hystogram.h src/Engine/Filters/GreyWorld.h src/Engine/Filters/Convolution.h src/Engine/Filters/Sobel.h src/Engine/Filters/Interpolation.h src/Engine/Filters/Manually.h src/Engine/Filters/Supplementary.h src/Engine/Filters/GaussianS.h .tmp/qPaint1.0.0/ && $(COPY_FILE) --parents src/GUI/gui.cpp src/GUI/ImageScene.cpp src/GUI/Validators.cpp src/ArgParser/arg_parser.cpp src/main.cpp src/Engine/Filter.cpp src/Engine/Engine.cpp src/Engine/Callback.cpp src/Engine/Filters/Hystogram.cpp src/Engine/Filters/GreyWorld.cpp src/Engine/Filters/Convolution.cpp src/Engine/Filters/Sobel.cpp src/Engine/Filters/Interpolation.cpp src/Engine/Filters/Manually.cpp src/Engine/Filters/Supplementary.cpp src/Engine/Filters/GaussianS.cpp .tmp/qPaint1.0.0/ && $(COPY_FILE) --parents src/GUI/gui.ui src/GUI/Manually.ui .tmp/qPaint1.0.0/ && (cd `dirname .tmp/qPaint1.0.0` && $(TAR) qPaint1.0.0.tar qPaint1.0.0 && $(COMPRESS) qPaint1.0.0.tar) && $(MOVE) `dirname .tmp/qPaint1.0.0`/qPaint1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qPaint1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_gui.cpp moc_ImageScene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gui.cpp moc_ImageScene.cpp
moc_gui.cpp: ui_gui.h \
		ui_Manually.h \
		src/Engine/Engine.h \
		src/Engine/Filter.h \
		src/Engine/Callback.h \
		src/GUI/ImageScene.h \
		src/GUI/Validators.h \
		src/GUI/gui.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/GUI/gui.h -o moc_gui.cpp

moc_ImageScene.cpp: src/GUI/ImageScene.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/GUI/ImageScene.h -o moc_ImageScene.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_gui.h ui_Manually.h
compiler_uic_clean:
	-$(DEL_FILE) ui_gui.h ui_Manually.h
ui_gui.h: src/GUI/gui.ui
	/usr/bin/uic-qt4 src/GUI/gui.ui -o ui_gui.h

ui_Manually.h: src/GUI/Manually.ui
	/usr/bin/uic-qt4 src/GUI/Manually.ui -o ui_Manually.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

gui.o: src/GUI/gui.cpp src/GUI/gui.h \
		ui_gui.h \
		ui_Manually.h \
		src/Engine/Engine.h \
		src/Engine/Filter.h \
		src/Engine/Callback.h \
		src/GUI/ImageScene.h \
		src/GUI/Validators.h \
		src/Engine/Filters/Hystogram.h \
		src/Engine/Filters/GreyWorld.h \
		src/Engine/Filters/Convolution.h \
		src/Engine/Filters/Sobel.h \
		src/Engine/Filters/Interpolation.h \
		src/Engine/Filters/Manually.h \
		src/Engine/Filters/Supplementary.h \
		src/Engine/Filters/GaussianS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gui.o src/GUI/gui.cpp

ImageScene.o: src/GUI/ImageScene.cpp src/GUI/ImageScene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageScene.o src/GUI/ImageScene.cpp

Validators.o: src/GUI/Validators.cpp src/GUI/Validators.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Validators.o src/GUI/Validators.cpp

arg_parser.o: src/ArgParser/arg_parser.cpp src/ArgParser/arg_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arg_parser.o src/ArgParser/arg_parser.cpp

main.o: src/main.cpp src/ArgParser/arg_parser.h \
		src/Engine/Engine.h \
		src/Engine/Filter.h \
		src/Engine/Callback.h \
		src/Engine/Filters/Convolution.h \
		src/Engine/Filters/Sobel.h \
		src/Engine/Filters/GreyWorld.h \
		src/Engine/Filters/Hystogram.h \
		src/Engine/Filters/Interpolation.h \
		src/Engine/Filters/Manually.h \
		src/Engine/Filters/Supplementary.h \
		src/Engine/Filters/GaussianS.h \
		src/GUI/gui.h \
		ui_gui.h \
		ui_Manually.h \
		src/GUI/ImageScene.h \
		src/GUI/Validators.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

Filter.o: src/Engine/Filter.cpp src/Engine/Filter.h \
		src/Engine/Callback.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Filter.o src/Engine/Filter.cpp

Engine.o: src/Engine/Engine.cpp src/Engine/Engine.h \
		src/Engine/Filter.h \
		src/Engine/Callback.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Engine.o src/Engine/Engine.cpp

Callback.o: src/Engine/Callback.cpp src/Engine/Callback.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Callback.o src/Engine/Callback.cpp

Hystogram.o: src/Engine/Filters/Hystogram.cpp src/Engine/Filters/Hystogram.h \
		src/Engine/Filter.h \
		src/Engine/Callback.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Hystogram.o src/Engine/Filters/Hystogram.cpp

GreyWorld.o: src/Engine/Filters/GreyWorld.cpp src/Engine/Filters/GreyWorld.h \
		src/Engine/Filter.h \
		src/Engine/Callback.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GreyWorld.o src/Engine/Filters/GreyWorld.cpp

Convolution.o: src/Engine/Filters/Convolution.cpp src/Engine/Filters/Convolution.h \
		src/Engine/Filter.h \
		src/Engine/Callback.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Convolution.o src/Engine/Filters/Convolution.cpp

Sobel.o: src/Engine/Filters/Sobel.cpp src/Engine/Filters/Sobel.h \
		src/Engine/Filters/Convolution.h \
		src/Engine/Filter.h \
		src/Engine/Callback.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Sobel.o src/Engine/Filters/Sobel.cpp

Interpolation.o: src/Engine/Filters/Interpolation.cpp src/Engine/Filters/Interpolation.h \
		src/Engine/Filter.h \
		src/Engine/Callback.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Interpolation.o src/Engine/Filters/Interpolation.cpp

Manually.o: src/Engine/Filters/Manually.cpp src/Engine/Filters/Manually.h \
		src/Engine/Filters/Convolution.h \
		src/Engine/Filter.h \
		src/Engine/Callback.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Manually.o src/Engine/Filters/Manually.cpp

Supplementary.o: src/Engine/Filters/Supplementary.cpp src/Engine/Filters/Supplementary.h \
		src/Engine/Filter.h \
		src/Engine/Callback.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Supplementary.o src/Engine/Filters/Supplementary.cpp

GaussianS.o: src/Engine/Filters/GaussianS.cpp src/Engine/Filters/GaussianS.h \
		src/Engine/Filter.h \
		src/Engine/Callback.h \
		src/Engine/Filters/Manually.h \
		src/Engine/Filters/Convolution.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GaussianS.o src/Engine/Filters/GaussianS.cpp

moc_gui.o: moc_gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gui.o moc_gui.cpp

moc_ImageScene.o: moc_ImageScene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImageScene.o moc_ImageScene.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

